"""Описание изменений

Revision ID: 8a0dbdbea68e
Revises: 
Create Date: 2025-05-26 08:13:16.345772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0dbdbea68e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_column('task')
        batch_op.drop_column('solution')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solution', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('task', sa.TEXT(), nullable=False))

    # ### end Alembic commands ###
